### ISSUE TITLE
unable to download sun360 dataset

### ISSUE THREAD

**Issue by varsha2906** [alexvbogdan/DeepCalib#10] opened 2020-07-02 12:37 UTC
from the link provided, i am unable to download sun360 dataset.
i am getting following issue "sun360.csail.mit.edu refused to connect."

can you tell me any other way to download

**Comment by GHYTyson** [comment] 2020-07-02 19:23
https://vcl.iti.gr/360-dataset/
This link may help. First fill the request form

**Comment by alexvbogdan** [comment] 2020-07-03 00:12
Duplicate of #2

**Closed** 2020-07-03 00:20 UTC
