### ISSUE TITLE
Why increase the size of the output image by 3 times？

### ISSUE THREAD

**Issue by shahow9527** [alexvbogdan/DeepCalib#12] opened 2020-09-23 03:41 UTC
Thank you for your reading! I encountered the following confusion when using your program: 
In the "undistSphIm.m", why do you want to change the size of the output image to 3 times the size of the input image? 

I have tried to keep the input and output the same size, and finally found that the field of view of the output image is only a small part of the input image. 
May I ask why this happened? Why set the magnification to 3 instead of other numbers? 
I am a beginner in this field, thank you for your help!

**Comment by alexvbogdan** [comment] 2020-09-23 09:54
Duplicate of #7

**Closed by alexvbogdan** 2020-09-23 09:54 UTC
