### ISSUE TITLE
Could you share the pre-trained model?

### ISSUE THREAD

**Issue by Cara-wuu** [alexvbogdan/DeepCalib#31] opened 2023-03-01 14:09 UTC
Hi ! Could you please share the pre-training model? I wanted to test it against my own experiment. Thank you very much!

**Comment by alexvbogdan** [comment] 2023-09-04 08:05
The link to weights is actually in the Readme, it is already available: https://github.com/alexvbogdan/DeepCalib#weights

**Comment by alexvbogdan** [comment] 2023-09-04 08:05
Duplicate of #13

**Closed as completed by alexvbogdan** 2023-09-04 08:05 UTC
Labels: duplicate
